# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 166)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonSync = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSync.setObjectName("pushButtonSync")
        self.gridLayout.addWidget(self.pushButtonSync, 3, 0, 1, 5)
        self.pushButtonAddDest = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddDest.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonAddDest.setObjectName("pushButtonAddDest")
        self.gridLayout.addWidget(self.pushButtonAddDest, 2, 2, 1, 1)
        self.comboBoxFrom = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxFrom.setObjectName("comboBoxFrom")
        self.gridLayout.addWidget(self.comboBoxFrom, 0, 1, 1, 1)
        self.pushButtonAddFrom = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddFrom.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonAddFrom.setObjectName("pushButtonAddFrom")
        self.gridLayout.addWidget(self.pushButtonAddFrom, 0, 2, 1, 1)
        self.comboBoxDest = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxDest.setObjectName("comboBoxDest")
        self.gridLayout.addWidget(self.comboBoxDest, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButtonClearFrom = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClearFrom.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonClearFrom.setObjectName("pushButtonClearFrom")
        self.gridLayout.addWidget(self.pushButtonClearFrom, 0, 4, 1, 1)
        self.pushButtonDeleteFrom = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteFrom.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonDeleteFrom.setObjectName("pushButtonDeleteFrom")
        self.gridLayout.addWidget(self.pushButtonDeleteFrom, 0, 3, 1, 1)
        self.pushButtonClearDest = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClearDest.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonClearDest.setObjectName("pushButtonClearDest")
        self.gridLayout.addWidget(self.pushButtonClearDest, 2, 4, 1, 1)
        self.pushButtonDeleteDest = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteDest.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonDeleteDest.setObjectName("pushButtonDeleteDest")
        self.gridLayout.addWidget(self.pushButtonDeleteDest, 2, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 4, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonSync.setText(_translate("MainWindow", "Sync"))
        self.pushButtonAddDest.setText(_translate("MainWindow", "+"))
        self.pushButtonAddFrom.setText(_translate("MainWindow", "+"))
        self.label_2.setText(_translate("MainWindow", "Destination"))
        self.label.setText(_translate("MainWindow", "Original"))
        self.pushButtonClearFrom.setText(_translate("MainWindow", "Clear"))
        self.pushButtonDeleteFrom.setText(_translate("MainWindow", "-"))
        self.pushButtonClearDest.setText(_translate("MainWindow", "Clear"))
        self.pushButtonDeleteDest.setText(_translate("MainWindow", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
